version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "5000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
